version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/sdk/client"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/sdk/hibernate-encryption"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/examples/demo-app-hibernate-encryption"
    schedule:
      interval: "weekly"
