groupId: "com.piiano.vault"
artifactId: "openapi"
artifactVersion: "1.2.1"
artifactDescription: "Generated client for the open API of Piiano vault"
artifactUrl: "https://piiano.com/docs/api"
apiPackage: "com.piiano.vault.client.openapi"
modelPackage: "com.piiano.vault.client.openapi.model"
invokerPackage: "com.piiano.vault.client.openapi"
booleanGetterPrefix: "is"
scmConnection: "scm:git:git@github.com/piiano/vault-java.git"
scmDeveloperConnection: "scm:git:git@github.com/piiano/vault-java.git"
scmUrl: "https://github.com/piiano/vault-java"
licenseName: "MIT License"
licenseUrl: "https://github.com/piiano/vault-java/blob/main/LICENSE"
developerName: "Piiano vault-java contributors"
developerEmail: "info@piiano.com"
developerOrganization: "Piiano"
developerOrganizationUrl: "https://piiano.com/"
