name: Publish generated openapi to maven
on:
  workflow_call:
    inputs:
      maven_version:
        type: string
        description: 'Maven version to release'
        required: true
      vault_version:
        type: string
        description: 'Vault version to release'
        required: true
    secrets:
      OSSRH_USERNAME:
        description: 'OSSRH Username'
        required: true
      OSSRH_TOKEN:
        description: 'OSSRH Token'
        required: true
      MAVEN_GPG_PRIVATE_KEY:
        description: 'GPG private key'
        required: true
      MAVEN_GPG_PASSPHRASE:
        description: 'GPG passphrase'
        required: true

  workflow_dispatch:
    inputs:
      maven_version:
        description: 'Maven version to release'
        required: true
      vault_version:
        description: 'Vault version for the release'
        required: true

jobs:
  build-n-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Java & Maven
        uses: actions/setup-java@v3
        with: # running setup-java again overwrites the settings.xml
          java-version: 8
          distribution: 'zulu'
          cache: 'maven'
          server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: OSSRH_USERNAME # env variable for username in deploy
          server-password: OSSRH_TOKEN # env variable for token in deploy
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import

      - name: Generate openapi
        run: |
          source VERSION
          cd sdk
          # update the generator config file with the required maven version
          sed -i "s/artifactVersion: \"$MAVEN_VERSION/artifactVersion: \"${{ inputs.maven_version }}/g" config.yaml
          cat config.yaml
          # update the makefile with the required vault version
          sed -i "s/VAULT_VERSION\s:=\s$MAVEN_VERSION/VAULT_VERSION\s:=\s${{ inputs.maven_version }}/g" Makefile
          cat Makefile
          # generate Java sdk for the openapi
          make generate-openapi
          sudo git apply patches/*.patch
          cat openapi/pom.xml

      - name: Build and publish openapi
        run: |
          sudo chmod -R 777 sdk/openapi
          cd sdk/openapi
          mvn clean deploy -B -P sign-artifacts -DskipTests
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
