name: Publish
run-name: ${{ github.workflow }} (${{ github.head_ref || github.ref_name }})

on:
  workflow_dispatch:
    inputs:
      vault_version:
        description: Vault version
        required: true
      bump-package:
        description: Bump maven version
        type: choice
        required: false
        default: patch
        options: [ none, patch, minor, major ]

jobs:
  build-n-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # By default, the ref is the commit hash that triggered the original workflow.
          # Meaning it is missing changes that are committed by the workflow itself.
          # Explicitly set ref to the branch name, so we pull the latest changes committed by the CI.
          ref: ${{ github.ref_name }}
          token: ${{ secrets.CICD_RELEASES_PAT }}

      - name: Set up Java & Maven
        uses: actions/setup-java@v3
        with: # running setup-java again overwrites the settings.xml
          java-version: 8
          distribution: 'zulu'
          cache: 'maven'
          server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: OSSRH_USERNAME # env variable for username in deploy
          server-password: OSSRH_TOKEN # env variable for token in deploy
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import

      - name: Update artifact version in config file for openapi
        if: inputs.bump-package != 'none'
        run: |
          source VERSION
          NEW_PUBLISH_VERSION=`npx --yes semver -i ${{ inputs.bump-package }} ${PUBLISH_VERSION}`
          sed -i "s/artifactVersion:\s\"${PUBLISH_VERSION}/artifactVersion: \"${NEW_PUBLISH_VERSION}/g" sdk/config.yaml

      - name: Generate openapi
        working-directory: sdk
        run: |
          source ../VERSION
          sed -i "s/VAULT_VERSION ?= ${VAULT_VERSION}/VAULT_VERSION ?= ${{ inputs.vault_version }}/g" Makefile
          make generate-openapi
          sudo chmod 777 ./openapi
          git apply patches/*.patch

      - name: Build openapi
        working-directory: sdk/openapi
        run: mvn clean install -B -DskipTests

#      - name: Publish openapi
#        if: inputs.bump-package != 'none'
#        working-directory: sdk/openapi
#        run: mvn clean deploy -B -P sign-artifacts -DskipTests
#        env:
#          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
#          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
#          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

      - name: Update version of client pom.xml
        if: inputs.bump-package != 'none'
        working-directory: sdk/client
        run: |
          source ../../VERSION
          NEW_PUBLISH_VERSION=`npx --yes semver -i ${{ inputs.bump-package }} ${PUBLISH_VERSION}`
          mvn versions:set -DnewVersion=${NEW_PUBLISH_VERSION}

      - name: Build client
        working-directory: sdk/client
        run: mvn clean install -B -DskipTests

      - name: Publish client
        if: inputs.bump-package != 'none'
        working-directory: sdk/client
        run: mvn clean deploy -B -P sign-artifacts -DskipTests
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

      - name: Update version of hibernate-encryption pom.xml
        if: inputs.bump-package != 'none'
        working-directory: sdk/hibernate-encryption
        run: |
          source ../../VERSION
          NEW_PUBLISH_VERSION=`npx --yes semver -i ${{ inputs.bump-package }} ${PUBLISH_VERSION}`
          mvn versions:set -DnewVersion=${NEW_PUBLISH_VERSION}

      - name: Build hibernate-encryption
        working-directory: sdk/hibernate-encryption
        run: mvn clean install -B -DskipTests

      - name: Publish hibernate-encryption
        if: inputs.bump-package != 'none'
        working-directory: sdk/hibernate-encryption
        run: mvn clean deploy -B -P sign-artifacts -DskipTests
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

      - name: Update demo-app-hibernate-encryption
        if: inputs.bump-package != 'none'
        working-directory: examples/demo-app-hibernate-encryption
        run: |
          source ../../VERSION
          NEW_PUBLISH_VERSION=`npx --yes semver -i ${{ inputs.bump-package }} ${PUBLISH_VERSION}`
          sed -i "s/<vault-java\.version>$PUBLISH_VERSION/<vault-java\.version>${NEW_PUBLISH_VERSION}/g" pom.xml

      - name: Update README files
        if: inputs.bump-package != 'none'
        run: |
          source VERSION
          sed -i "s/compatible with Vault ${VAULT_VERSION}/compatible with Vault ${{ inputs.vault_version }}/g" sdk/README.md sdk/client/README.md sdk/hibernate-encryption/README.md

      - name: Update VERSION file
        if: inputs.bump-package != 'none'
        run: |
          source VERSION
          NEW_PUBLISH_VERSION=`npx --yes semver -i ${{ inputs.bump-package }} ${PUBLISH_VERSION}`
          echo -e 'PUBLISH_VERSION="${NEW_PUBLISH_VERSION}"\nVAULT_VERSION="${{ inputs.vault_version }}"' > VERSION

      - name: Commit version changes and push
        if: inputs.bump-package != 'none'
        run: |
          git config --global user.email "cicd@piiano.com"
          git config --global user.name "Github Actions"
          git add VERSION
          git add sdk/client/pom.xml
          git add sdk/hibernate-encryption/pom.xml
          git add sdk/config.yaml
          git add sdk/Makefile
          git add examples/demo-app-hibernate-encryption/pom.xml
          source VERSION
          git commit -m "Update publish version to ${PUBLISH_VERSION} and vault version to ${VAULT_VERSION}"
          git push
