name: Test all
run-name: ${{ github.workflow }} (${{ github.head_ref || github.ref_name }})

on:
  push:
    # Run for all branches excluding dependabot branches. Do NOT run for tags.
    branches-ignore:
      - "dependabot/**"

jobs:
  test-sdk:
    runs-on: ubuntu-latest
    services:
      vault:
        image: piiano/pvault-dev:latest
        env:
          PVAULT_SERVICE_LICENSE: ${{ secrets.PVAULT_SERVICE_LICENSE }}
          PVAULT_SENTRY_ENABLE: true
          PVAULT_LOG_CUSTOMER_IDENTIFIER: "piiano"
          PVAULT_LOG_CUSTOMER_ENV: "VAULT-JAVA"
        ports:
          - 8123:8123
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install java
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: zulu
          cache: maven

      - name: Build all
        working-directory: sdk
        run: make

      - name: Test client
        working-directory: sdk/client
        run: mvn test

      - name: Test hibernate-encryption
        working-directory: sdk/hibernate-encryption
        run: mvn test
